; ===============================
; Structure obligatoire du projet
; ===============================

; Wifinfo-projet/
;  ├── src/         ← les sources .ino .cpp et .h ici !
;  ├── data/        ← le répertoire data ici !
;  ├── include/     ← rien
;  ├── lib/         ← rien : elles seront téléchagées automatiquement
;  ├── platformio.ini
;  ├── rename_firmware.py   ← ici !
;  ├── release/   ← sera créé automatiquement

; Résultats de la compilation ( Build et Build Filesystem Image)
;   .pio/build/<nom de l'environnement>/firmware.bin
;   .pio/build/<nom de l'environnement>/spiffs.bin

; Upload (Upload et Upload Filesystem Image)

[platformio]
default_envs =
    Wifinfo_esp8266_devkit
    Wifinfo_esp8266_d1_mini
    Wifinfo_esp32_devkit
    Wifinfo_esp32_d1_mini
    Wifinfo_esp32s2_wemos
    Wifinfo_esp32c3_wemos
    Wifinfo_esp32s3_wemos

[env]
extra_scripts =
    rename_firmware.py
    rename_spiffs.py
    fullflash.py

[env:tools]
platform = native
extra_scripts = build_all_fs.py
build_src_filter = -<*>

; ============================
; ESP8266 DevKit (NodeMCU v2/v3)
; ============================
[env:Wifinfo_esp8266_devkit]
platform = espressif8266@4.2.1
board = nodemcuv2
framework = arduino

board_build.f_cpu = 160000000L
board_build.filesystem = spiffs
board_build.ldscript = eagle.flash.4m1m.ld

lib_deps =
    makuna/NeoPixelBus@^2.8.4
    https://github.com/Duglof/LibTeleinfo.git
    knolleary/PubSubClient@2.8
    https://github.com/Duglof/LibTeleinfo/raw/esp32/librairie/Syslog-master.zip

build_flags =
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY

; ============================
; ESP8266 — Core 3.1.2
; ============================
[env:Wifinfo_esp8266_d1_mini]
platform = espressif8266@4.2.1
board = d1_mini
framework = arduino
board_build.f_cpu = 160000000L
board_build.filesystem = spiffs
; Description des differentes partitions possibles :
; Voir répertoire .pio/packages/framework-arduinoespressif8266/tools/sdk/ld/
;   - eagle.flash.4m1m.ld → 4MB flash, 1MB SPIFFS
;   - eagle.flash.4m2m.ld → 4MB flash, 2MB SPIFFS
;   - eagle.flash.1m.ld → 1MB flash
;   - etc ...
; Upload des data : PlatformIO → Upload Filesystem Image
; Pour même config que arduino IDE : Flash size : 4MB (FS 1MB / OTA :~ 1019KB)
board_build.ldscript = eagle.flash.4m1m.ld

lib_deps =
    makuna/NeoPixelBus@^2.8.4
    https://github.com/Duglof/LibTeleinfo.git
    knolleary/PubSubClient@2.8
    https://github.com/Duglof/LibTeleinfo/raw/esp32/librairie/Syslog-master.zip

build_flags =
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY


; ============================
; ESP32 — Arduino Core 3.1.1
; ============================
[env:Wifinfo_esp32_devkit]
platform = espressif32@6.6.0
board = esp32dev
framework = arduino
board_build.f_cpu = 160000000L
board_build.filesystem = spiffs
; Description des differentes partitions possibles :
; Voir dossier <home>.platformio/packages/framework-arduinoespressif32/tools/partitions
; Partition identique à "Default 4MB with spiffs"
;board_build.partitions = default_4MB.csv
board_build.partitions = default.csv


lib_deps =
    makuna/NeoPixelBus@^2.8.4
    https://github.com/Duglof/LibTeleinfo.git
    https://github.com/Pedroalbuquerque/ESP32WebServer
    knolleary/PubSubClient@2.8
    https://github.com/Duglof/LibTeleinfo/raw/esp32/librairie/Syslog-master.zip

build_flags =
    -D CONFIG_ARDUINO_RUNNING_CORE=1
    -D CONFIG_ARDUINO_EVENT_RUNNING_CORE=1

; ============================
; ESP32 Mini D1 — Arduino Core 3.1.1
; ============================
[env:Wifinfo_esp32_d1_mini]
platform = espressif32@6.6.0
board = wemos_d1_mini32
framework = arduino
board_build.f_cpu = 160000000L
; Système de fichiers
board_build.filesystem = spiffs

; Voir dossier <home>.platformio/packages/framework-arduinoespressif32/tools/partitions
; Partition identique à "Default 4MB with spiffs"
board_build.partitions = default.csv

; Flags spécifiques ESP32
build_flags =
    -D CONFIG_IDF_TARGET_ESP32

lib_deps =
    makuna/NeoPixelBus@^2.8.4
    https://github.com/Duglof/LibTeleinfo.git
    https://github.com/Pedroalbuquerque/ESP32WebServer
    knolleary/PubSubClient@2.8
    https://github.com/Duglof/LibTeleinfo/raw/esp32/librairie/Syslog-master.zip

; ============================
; ESP32-S2 WeMos (S2 Mini)
; ============================
[env:Wifinfo_esp32s2_wemos]
platform = espressif32@6.6.0
;board = lolin_s2_mini    => ne compile pas
board = esp32-s2-saola-1
framework = arduino

; CPU à 160 MHz comme tes autres ESP32
board_build.f_cpu = 160000000L

; Système de fichiers SPIFFS
board_build.filesystem = spiffs

; Voir dossier <home>.platformio/packages/framework-arduinoespressif32/tools/partitions
; Partition identique à "Default 4MB with spiffs"
board_build.partitions = default.csv

; Flags spécifiques ESP32-S2
build_flags =
    -D CONFIG_IDF_TARGET_ESP32S2 

lib_deps =
    makuna/NeoPixelBus@^2.8.4
    https://github.com/Duglof/LibTeleinfo.git
    https://github.com/Pedroalbuquerque/ESP32WebServer
    knolleary/PubSubClient@2.8
    https://github.com/Duglof/LibTeleinfo/raw/esp32/librairie/Syslog-master.zip

; ============================
; ESP32-C3 WeMos (LOLIN C3 Mini)
; ============================
[env:Wifinfo_esp32c3_wemos]
platform = espressif32@6.6.0
board = lolin_c3_mini
framework = arduino

; CPU à 160 MHz (le C3 supporte 80 ou 160 MHz)
board_build.f_cpu = 160000000L

; Système de fichiers SPIFFS
board_build.filesystem = spiffs

; Voir dossier <home>.platformio/packages/framework-arduinoespressif32/tools/partitions
; Partition identique à "Default 4MB with spiffs"
board_build.partitions = default.csv

; Flags spécifiques ESP32-C3 (RISC-V + USB natif)
build_flags =
    -D CONFIG_IDF_TARGET_ESP32C3

lib_deps =
    makuna/NeoPixelBus@^2.8.4
    https://github.com/Duglof/LibTeleinfo.git
    https://github.com/Pedroalbuquerque/ESP32WebServer
    knolleary/PubSubClient@2.8
    https://github.com/Duglof/LibTeleinfo/raw/esp32/librairie/Syslog-master.zip

; ============================
; ESP32-S3 WeMos (LOLIN S3 Mini)
; ============================
[env:Wifinfo_esp32s3_wemos]
platform = espressif32@6.6.0
board = lolin_s3_mini
framework = arduino

; CPU à 160 MHz comme tes autres ESP32
board_build.f_cpu = 160000000L

; Système de fichiers SPIFFS
board_build.filesystem = spiffs

; Voir dossier <home>.platformio/packages/framework-arduinoespressif32/tools/partitions
; Partition identique à "Default 4MB with spiffs"
board_build.partitions = default.csv

; Flags spécifiques ESP32-S3 (USB natif + dual-core)
build_flags =
    -D CONFIG_IDF_TARGET_ESP32S3
 
lib_deps =
    makuna/NeoPixelBus@^2.8.4
    https://github.com/Duglof/LibTeleinfo.git
    https://github.com/Pedroalbuquerque/ESP32WebServer
    knolleary/PubSubClient@2.8
    https://github.com/Duglof/LibTeleinfo/raw/esp32/librairie/Syslog-master.zip

